### ISSUE TITLE
mocker.patch on function

### ISSUE THREAD

**Issue by ulyssejdv** [pytest-dev/pytest-mock#117]
Hi,
When I want to mock a function in a module, the mock not work if I use this syntax : 

from mypkg.mymodule import myfunction
+ myfunction()

but work with this one :

from mypkg import mymodule
+mymodule.myfunction()

Any idea ?

**Comment by nicoddemus** [comment]
@ulyssejdv that is related to how mock works. There's a good explanation [here](https://docs.python.org/3/library/unittest.mock.html#where-to-patch).

I'm closing this for now but feel free to follow up with further questions. 👍

**Comment by kaldown** [comment]
Just wonder.
If there any way to patch by definition, in a case where the function being imported relatively?

**Comment by nicoddemus** [comment]
Mocking works by replacing the attribute, so if a module already imported a function, it already has a reference to it, changing the original reference doesn't work.

I guess it _might_ be possible to change the actual function object instead of changing the reference, but they are immutable on the Python side and might require a C extension. However I definitely wouldn't go down that route. 😁
