### ISSUE TITLE
mocker fixture cannot be used in module scope

### ISSUE THREAD

**Issue by aleGpereira** [pytest-dev/pytest-mock#136]
If i define a custom fixture like:

@pytest.fixture(scope='module')
def my_fixture(mocker):
    // code using mocker

class TestMyModule(object):

    def test_one(self, my_fixture):
        // test code

When i run this i get:
ScopeMismatch: You tried to access the 'function' scoped fixture 'mocker' with a 'module' scoped request object, involved factories

I'm i doing something wrong to do something like this? is there some reason why this is not supported?

Thanks.

**Comment by nicoddemus** [comment]
Hi @aleGpereira,

This is a pytest limitation I'm afraid, `mocker` is a function-scoped fixture so it cannot be used in higher scopes.

A proposal for a new "invocation-scoped" fixture is proposed in https://github.com/pytest-dev/pytest/issues/1681, but the implementation for that has been pulled back because we encountered some severe problems with the implementation right before a release.

For your module-scope fixture, an alternative is to fallback is the `unittest.mock` module directly, using a `with` statement.

Cheers,

**Comment by schollii** [comment]
A major reason for using mocker is to avoid 4-level deep "with" blocks when patching multiple functions; often using "with" is not very nice. I use the following trick: instead of using nested "with" statements, I define a nest function because I can then define the "mock.patch" as decorators. So instead of:
```
def test_something(): 
    ...
    with mock.patch(...): 
        with mock.patch(...):
            with mock.patch(...):
                with mock.patch(...):
                     ...
```
I use this: 
```
def test_something(): 
    ...
    @mock.patch(...)
    @mock.patch(...)
    @mock.patch(...)
    @mock.patch(...)
    def inner_func(_1, _2, _3, _4):
        ...
```
This is better but the nice thing with mocker, is you don't have to worry about additional call params which you may not even care about (often _1, _2 etc are not used).

**Comment by matthewatabet** [comment]
A simple solution to this could be to provide `mocker_session` and `mocker_module` fixtures.

**Comment by doandzhiFt** [comment]
Greetings! Is there any progress with this one?

**Comment by nicoddemus** [comment]
Hi @doandzhiFt,

Not really I'm afraid, but I will gladly review and merge a PR that adds `mock_session`, `mock_class` and `mock_module` fixtures. :grin:

**Comment by scorphus** [comment]
Ping, @nicoddemus

**Comment by nicoddemus** [comment]
Hi @scorphus, sorry for the delay.

I've just merged your patch and will make a release shortly, thanks a lot for the contribution, I appreciate it greatly. 👍

**Comment by nicoddemus** [comment]
Published in `3.1.0`, thanks!

**Comment by aleGpereira** [comment]
Great work, thanks guys!

**Comment by scorphus** [comment]
Glad it's useful to you too, @aleGpereira!

Thanks again for the new release, @nicoddemus!

Open source is amazing! Just a few days ago I tried to use `mocker` in a session-scoped fixture and found this issue. This coming week there's going to be code on production tested by a session-scoped fixture using `mocker` YAY 🎉🙌

**Comment by featureoverload** [comment]
I had the same problem.

**Comment by pawelad** [comment]
> It would be good to mention this in the docs - I'll try to open a PR when I have some time.

Actually, it's already in there, I just somehow missed it (twice?):

https://github.com/pytest-dev/pytest-mock/blob/e023728d398bcabd24a81d1b0249aabb0e2a460f/docs/usage.rst?plain=1#L39-L45
