### ISSUE TITLE
Question about tearDown vs addCleanup

### ISSUE THREAD

**Issue by pandichef** [pytest-dev/pytest-mock#198]
I was just watching this solid presentation by Lisa Roach: [Demystifying the Patch Function](https://youtu.be/ww1UsGZV8fQ?t=904).

She makes it a point that patch.stopall() should be used with addCleanup rather than tearDown.  In pytest, I believe this is the equivalent of using [fixture finalization](https://docs.pytest.org/en/documentation-restructure/how-to/fixture.html#fixture-finalization-executing-teardown-code) rather than a yield fixture.

In pytest-mock, it seems like mocker is using a yield fixture and stopall() being called after the yield.   Is that the case?   If so, how should I think about this package in the context of her comments?  At face value, this seems like a concern, but maybe I'm missing something.

Thank you

**Comment by nicoddemus** [comment]
Hi @pandichef,

I did not watch the talk, but in our case the patch object is created and destroyed by a fixture, which is the correct approach.

`addCleanup` is superior to `tearDown` because it can be used right after each resource is created, and they will be destroyed correctly and in the correct order, even if `setUp` fails. It is also possible to create resources inside a test and have them being properly disposed:

```python
class Test:

    def setUp(self):
        self.resource1 = Resource(...)
        self.addCleanup(self.resource1.close)

        self.resource2 = Resource(...)
        self.addCleanup(self.resource2.close)

    def test_foo(self):
        resource3 = Resource(...)
        self.addCleanup(resouce3.close)
``` 

Here everything is cleaned up properly even in face of exceptions.

The `tearDown` method is not called if `setUp` fails, and having `tearDown` cleanup resources created inside tests is clumsy:

```python
class Test:

    def setUp(self):
        self.resource1 = Resource(...)
        self.resource2 = Resource(...)

    def tearDown(self):
        self.resource1.close() 
        self.resource2.close()
        if hasattr(self, "resource3"):
            self.resource3.close()

    def test_foo(self):
        self.resource3 = Resource(...)        
``` 

Here if we get an exception creating `self.resource2`, `tearDown` will never get executed, so `self.resource1` will leak. Also the `hasattr` trick above does not scale if each test has different needs.

In moder code, I would advise to never use `tearDown` at all, always using `addCleanup` instead.

pytest fixtures follow the same principle as `addCleanup`, meaning that if a fixture was successfully created, it will be destroyed, regardless if other fixtures fail.

```python
def test_foo(resource1, resource2):
    ...
```

Here even if `resource2` raises an error during creation, `resource1` will be destroyed properly.

I'm closing this for now but feel free to follow with further questions. 👍

**Comment by pandichef** [comment]
Thank you for the detailed explanation!  I assume this [comment from asottile ](https://github.com/pytest-dev/pytest/issues/4576) is wrong then:  "I don't like using (pytest-mock) due to the same reasons I mentioned about scoping of patches in monkeypatch"?

Also, I noticed the mocker fixture can be accessed in a regular doctest (in a non-test file) using `mocker = getfixture('mocker')`.  Can you explain how `pytest-mock` enables accessing a fixture in a non-test file?  When I try to simulate `pytest-mock` using this custom fixture, I get a FixtureLookupError exception:

```python
@pytest.fixture
def mymock(request):
    request.addfinalizer(patch.stopall)  # ensures that mocks are destroyed if test fails at any point
    m = patch('pandas.DataFrame.to_excel', autospec=True).start()
    return m
```

(I realized this is a bit outside the scope of `pytest-mock`, so thank you in advance for indulging me.)

**Comment by nicoddemus** [comment]
I suppose you mean this bit:

> CON: as it's a fixture, the scope is often more broad than expected instead of "just part of the function" or "just the function", it can often lead to patches "leaking" into other fixtures / etc. It's also difficult to control the ordering in some cases
ok this isn't strictly fair, there is a context manager version, it's just not the "default style"

@asottile is talking here about how `monkeypatch`/`mocker`, as fixtures, apply all their mocking to the entire test function and other fixtures being involved. Personally I don't find this to be a problem in general, except for very sensitive functions that you want to mock around the less amount of code possible, but of course that's a matter of opinion.

> Can you explain how pytest-mock enables accessing a fixture in a non-test file?

This happens because the `mocker` fixture is installed by a plugin, hence it is global. Your fixture is probably declared in a `conftest.py` file outside the tree where the doctest code is declared, so that file can't "see" `mymock`.

Hope this helps!

**Comment by pandichef** [comment]
It's super helpful.  Thanks again!  I actually have one more question that kind-of/sort-of belongs here...

I feel like I often have two jobs when writing unit tests.  First, I have to identify the stuff that creates side effects.  Next, I have to write the mocks for those side effects.  This isn't too bad when writing new code, but can be absolutely brutal when writing unit tests legacy code.

Do you know of any utilities for "side effect introspection"?  And, if not, is this a feature that could be a part of pytest-mock at some point?

For example, maybe you could mark a test as `@pytest,mark.no_side_effect` and the test would fail if a side effect was found.  And if you only want to test for file I/O and network access (e.g., MySQL database), then mark would be specified as `@pytest.mark.no_side_effect(type=['fileio', 'network'])`.

**Comment by nicoddemus** [comment]
> This isn't too bad when writing new code, but can be absolutely brutal when unit testing legacy code.

Yes, because often that code is not "unittest-friendly" and hard-codes dependencies. Often if a function/method requires a ton of mocking, it might be a sign of a coupled design.

> Do you know of any utilities for "side effect introspection"? 

There are a few mock-related utilities that target specific libraries (for example `responses` with `requests`), but I'm not familiar with any general purpose solution.

> And, if not, is this a feature that could be a part of pytest-mock at some point?

Perhaps, but I don't have plans for it at the moment.

Cheers!
